plotdir: Plots-MAGIC

jsonfile: WS2003-23.json
#jsonfile: WS2023-24.json
#jsonfile: WS_detailed.json

#h5file_short: WS_detailed.h5
#h5file_short: WS2003-23_short_withstate.h5
h5file_short: WS2023-24_short.h5
h5file_long: WS2003-24_long.h5
#h5file_long: WS2003-23_long_with60min.h5
#h5file_long: WS2003-24_long.h5
#h5file_long: WS_detailed_long.h5

h5file_corr: WS2003-23_corr.h5

data_spacing_minutes: 2

is_20to22: True
tits: '_2024'

longitude: -17.8907 * u.deg
latitude: 28.7619 * u.deg


name_temperature: temperature
name_humidity:    humidity
name_pressure:    pressure
name_ws_current:  windSpeedCurrent
name_ws_gust:     windGust
name_ws_average:  windSpeedAverage
name_wdir_current: windDirection
name_wdir_average: windDirectionAverage

# from: https://ftp.cpc.ncep.noaa.gov/cwlinks/norm.daily.nao.cdas.z500.19500101_current.csv
is_naoi: true
naoi_file: norm.daily.nao.cdas.z500.19500101_current.csv
not_file: NOT_2003_2023.csv
h5file_not: NOT_2003_2023.h5

coverage_cut: 50
coverage_cut_for_daily_samples: 10
coverage_cut_for_monthly_samples: 80
day_coverage_for_samples: 85  # in percent
day_coverage_for_pressure: 90

wind_binning: np.concatenate((np.arange(0.,104.,4.)-0.5,105.2 + 4*(np.arange(0,10)-0.5) + 0.3*(np.arange(0,10)-0.5)**2),axis=None) 

WS_start: 2003-01-01 00:00:01
WS_end:  2023-12-31 23:59:59
WS_relocation: 2004-03-01 00:00:01
new_WS: 2007-03-20 00:00:01
new_model: 2017-04-10 00:00:01
old_model: 2023-01-16 00:00:01
NOT_end_of_5min: 2007-02-02 12:00:00
NOT_end_of_data: 2019-12-31 23:59:59
str_NOT_interval: only 2007-2019

# pressure
minimum_pressure: 750
maximum_pressure: 850

# DTR
is_DTR_offset: true
is_DTR_averaging: true
is_DTR_NOT: true
is_DTR_humcorr: true
is_DTR_dCm: true
is_DTR_profile2d: true
avg_n_DTR: 5
freq_n_DTR: 11min
offset_from_temperature: 0.051    # result of offset analysis from plot-temperature
day_coverage_for_diurnal: 95

# temperature
minimum_temperature: -15
maximum_temperature: 40

# humidity
is_humidity_offset: false
is_humidity_20to22: true
is_humidity_NOT: true

# Initialize likelihoods
is_coauthor_tests: true
is_temperature_offset: false
is_temperature_hessian: true
is_temperature_NOT: true

init_temperature: np.array([10.6, 0., 6.5, 6.9, 3.0])
init_temperature_dphim: np.array([10.6, 0., 6.5, 6.9, 0., 3.0])
init_temperature_dCm: np.array([10.6, 0., 6.5, 6.9, 0., 3.0]) 
init_temperature_monthly: np.array([10.6, 0., 6.5, 4.2, 1.9])
init_temperature_offset: np.array([6.3, 0., 6., 7., 3.2, 0.]) 

init_mu2_pressure: np.array([786., 0., 5.6, 6.6, 4.2, 9.0, 3.1])
init_mu2_sig2_offset_pressure: np.array([786., 0., 5.6, 6.6, 4.2, 9.0, 3.1, -1.0, 4.0, 0.])
init_mu2_sig2_pressure: np.array([786., 0., 5.6, 6.6, 4.2, 9.0, 3.1, -1.0, 4.0])
init_mu2_offset_pressure: np.array([786., 0., 5.6, 6.6, 4.2, 9.0, 3.1, 0.])
init_month_pressure: np.array([786., 0.,5.4,6.6,4.0, 8.9, 1.6])

init_DTR: np.array([8.2, 0., 0.9, 5.9, 0.7])
init_DTR_nob: np.array([8.2, 0.9, 5.9, 0.7])
init_DTR_dphim: np.array([8.2, 0., 0.9, 5.9, 0., 0.7])
init_DTR_dCm: np.array([8.2, 0., 0.9, 5.9, 0., 0.7])
init_DTR_offset: np.array([8.2, 0., 0.9, 5.9, 0.7, 0.])    

is_humidity_hessian: true
init_hum: np.array([30., 0., 6.5, 9.9, 10.0])    
init_hum2: np.array([31.5, 0.,25.4, 1.2, 33., 7.6, 26.3])
init_hum4: np.array([24.5, 0.,20.8, 3.8, 26., 6.9, 17.1, -2.6, 3.1])
init_hum2_offset: np.array([31.5, 0.,25.4, 1.2, 33., 7.6, 26.3,0.])
init_hum_month: np.array([28., 0.,20., 3.7, 24., 7., 17.])
